---
name: Rust

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:

jobs:
  build:
    uses: https://github.com/famedly/github-workflows/.github/workflows/rust.yml@main
    secrets: inherit
